feat #12: added ability to manage block state
icerockdev/moko-web3 pull request #13
Opened 2021-07-23 10:03 UTC by y9san9

2021-07-23 10:40 UTC, Alex009 requested changes

2021-07-23 10:40 UTC, Alex009 commented on web3/src/commonMain/kotlin/dev.icerock.moko.web3/BlockState.kt
> +interface BlockState {
Sealed interface will be better here

2021-07-23 10:40 UTC, Alex009 commented on web3/src/commonMain/kotlin/dev.icerock.moko.web3/BlockState.kt
> +package dev.icerock.moko.web3
Copyright required

2021-07-23 10:54 UTC, y9san9 commented on web3/src/commonMain/kotlin/dev.icerock.moko.web3/BlockState.kt
> +package dev.icerock.moko.web3
Added

2021-07-26 04:21 UTC, y9san9 commented on web3/src/commonMain/kotlin/dev.icerock.moko.web3/BlockState.kt
> +interface BlockState {
Added

2021-07-26 05:33 UTC, Alex009 approved these changes

2021-07-26 05:34 UTC, merged