#85: add string serializer
icerockdev/moko-web3 pull request #87
Opened 2021-11-19 08:59 UTC by denmusic1992

Add possibility to encode dynamic string type

2021-11-19 09:53 UTC, y9san9 requested changes

2021-11-19 09:53 UTC, y9san9 commented on web3/src/commonMain/kotlin/dev.icerock.moko.web3/contract/StringParam.kt
> +class StringParam : DynamicEncoder<String> {
Make StringParam object, since it's no reason to keep it as class

2021-11-19 11:38 UTC, y9san9 approved these changes

2021-11-22 03:16 UTC, anton6tak commented on web3/src/commonMain/kotlin/dev.icerock.moko.web3/contract/StringParam.kt
> +package dev.icerock.moko.web3.contract
Copyright please

2021-11-22 06:27 UTC, denmusic1992 commented on web3/src/commonMain/kotlin/dev.icerock.moko.web3/contract/StringParam.kt
> +package dev.icerock.moko.web3.contract
added

2021-11-22 08:15 UTC, merged